"""Renderers for the deployment assets `init` generates (#16).

Templates are Python functions returning strings (not files in a data dir), so
they need no package-data wiring and are trivially unit-testable. The generated
image is a **single container** (ADR-0011): it installs ``streamlit-private[gateway]``
and runs ``python -m streamlit_private.gateway``, which launches Streamlit bound
to loopback and exposes **only** the gateway port. The container targets Python
3.12 (ADR-0012), independent of the CLI's own floor.
"""

from __future__ import annotations

# Default Streamlit entry file for newly-scaffolded projects.
DEFAULT_APP = "streamlit_app/app.py"


def dockerfile(app_path: str = DEFAULT_APP) -> str:
    """Single-container image: gateway + Streamlit, only the gateway port exposed."""
    return f"""\
# Generated by streamlit-private. Single-container image (ADR-0011):
# the gateway runs Streamlit bound to 127.0.0.1 and proxies it; only the
# gateway port is published. Targets Python 3.12 (ADR-0012).
FROM python:3.12-slim

WORKDIR /app

# Install the user's deps plus the streamlit-private gateway (referenced, not
# vendored — security fixes ship via a version bump here).
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt "streamlit-private[gateway]"

COPY . .

# The Streamlit entry file the gateway launches on loopback. Override per repo.
ENV SP_APP={app_path}

# Only the gateway port is exposed. Streamlit binds 127.0.0.1:8501 (never published).
EXPOSE 8000

CMD ["python", "-m", "streamlit_private.gateway"]
"""


def railway_toml() -> str:
    """Railway build/deploy config. Railway injects $PORT, which the gateway reads."""
    return """\
# Generated by streamlit-private for Railway.
[build]
builder = "dockerfile"

[deploy]
# The Dockerfile CMD runs the gateway; Railway injects PORT.
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
"""


def dockerignore() -> str:
    return """\
.git
.venv
venv
__pycache__
*.pyc
.env
.streamlit/secrets.toml
"""


def env_example(auth_provider: str, hosting_provider: str, app_path: str = DEFAULT_APP) -> str:
    """Document the env var contract the gateway entrypoint reads.

    These are set on the hosting provider (never committed). Auth/hosting names
    are interpolated so the file reflects the chosen providers.
    """
    return f"""\
# streamlit-private environment ({auth_provider} auth, {hosting_provider} hosting).
# Copy to `.env` for local runs and set these on your host for deploys.
# NEVER commit a filled-in .env — these are secrets.

# --- Gateway ---
# Public port the gateway listens on. Railway injects PORT automatically.
PORT=8000
# The Streamlit entry file the gateway launches (bound to 127.0.0.1:8501).
SP_APP={app_path}
# Public origin users hit, e.g. https://my-app.up.railway.app. Used for XSRF
# origin checks and Clerk authorized_parties.
PUBLIC_URL=
# HMAC secret for the gateway's __sp_session correlation cookie. Generate once,
# e.g. `python -c "import secrets; print(secrets.token_urlsafe(32))"`, and pin it
# (a changed secret forces all sessions to re-handshake).
SP_SESSION_SECRET=

# --- Clerk (auth) ---
# Instance JWT public key (PEM) for networkless session verification.
CLERK_JWT_KEY=
# Clerk hosted Account Portal sign-in URL, e.g. https://accounts.<domain>.com/sign-in
CLERK_SIGN_IN_URL=
# Organization whose membership grants access. Leave blank to allow any signed-in user.
CLERK_REQUIRED_ORG_ID=
# Clerk Backend API secret key (used by invite / access-request commands).
CLERK_SECRET_KEY=
"""


def streamlit_private_notes(auth_provider: str, hosting_provider: str, app_path: str) -> str:
    """A notes file added to EXISTING repos (we never edit the user's README)."""
    return f"""\
# streamlit-private

This repository has been wrapped by [`streamlit-private`](https://github.com/DecisionNerd/streamlit-private)
to deploy your Streamlit app privately behind {auth_provider} authentication on {hosting_provider}.

**Your application code was not modified.** Only infrastructure was added:

- `streamlit-private.yaml` — the project manifest (providers, source of truth).
- `Dockerfile` — single-container image (gateway + Streamlit; only the gateway port is exposed).
- `railway.toml` — {hosting_provider} build/deploy config.
- `.env.example` — the environment variables to set on your host (see comments).
- `.dockerignore`.

## Next steps

1. Confirm `SP_APP` in `.env.example` points at your Streamlit entry file
   (detected: `{app_path}` — override if wrong).
2. Set the environment variables on your host
   (especially `CLERK_*`, `PUBLIC_URL`, `SP_SESSION_SECRET`).
3. Deploy: `uvx streamlit-private deploy {hosting_provider}`.

To change providers or regenerate these files: `uvx streamlit-private init --force`.
"""


def starter_app() -> str:
    """A minimal multipage starter app for empty projects (self-detects as Streamlit)."""
    return """\
import streamlit as st

st.set_page_config(page_title="My private app", page_icon="🔒")
st.title("My private Streamlit app")
st.write(
    "This app is wrapped by streamlit-private — authenticated and ready to deploy. "
    "Edit `streamlit_app/app.py` to build it out."
)
"""


def starter_page() -> str:
    """A demo page so the generated project exercises Streamlit multipage."""
    return """\
import streamlit as st

st.title("Example page")
st.write("Add pages under `streamlit_app/pages/` and they appear in the sidebar.")
"""


def starter_requirements() -> str:
    """requirements.txt for a brand-new project (existing repos keep their own)."""
    return "streamlit\n"


def starter_readme(auth_provider: str, hosting_provider: str) -> str:
    """README for a brand-new project (only written when absent)."""
    return f"""\
# My private Streamlit app

Scaffolded by [`streamlit-private`](https://github.com/DecisionNerd/streamlit-private):
a Streamlit app behind {auth_provider} authentication, ready to deploy on {hosting_provider}.

## Develop

```bash
pip install -r requirements.txt
streamlit run streamlit_app/app.py
```

## Deploy privately

1. Set the environment variables from `.env.example` on your host.
2. `uvx streamlit-private deploy {hosting_provider}`

Reconfigure providers with `uvx streamlit-private init --force`.
"""
